CRM-18518/ provoke new build with minor changes
kronostechnologies/docker-clamav pull request #6
Opened 2023-02-27 13:44 UTC by paulmillette-equisoft

[CRM-18518](https://jira.equisoft.com/browse/CRM-18518)

nous créerons un nouveau tag [ici](https://github.com/kronostechnologies/docker-clamav/tags) après la merge

2023-02-27 14:16 UTC, pylafleur commented
En fait, tant qu'à faire ça, on pourrait mettre en place le build périodique (voir les workflows de [docker-equisoft-connect](https://github.com/equisoft/docker-equisoft-connect)).

2023-02-27 18:38 UTC, etremblay commented
> En fait, tant qu'à faire ça, on pourrait mettre en place le build périodique (voir les workflows de [docker-equisoft-connect](https://github.com/equisoft/docker-equisoft-connect)).

J'ai demandé de le faire en 2 temps pour être certain que le build fonctionne avant.

2023-02-27 18:41 UTC, etremblay requested changes

2023-02-27 18:41 UTC, etremblay commented on .github/workflows/docker.yml
> +          - "crm-base"
tu as pas besoin d'une matrice,  ce repo as une seule image.

Aussi, le nom de l'image n'est pas crm, je pense que c'est `clamav`

2023-02-27 18:41 UTC, etremblay commented on .github/workflows/docker.yml
> +          registry: ${{ secrets.ECR_REGISTRY }}
si tu regarde l'ancien build, il publie sur ghcr, pas sur ecr.  

Je sais pas si on a des exemple de repos qui publie sur ghcr avec notre action 

@kronostechnologies/harmony  ?

2023-03-06 15:03 UTC, etremblay commented on .github/workflows/docker.yml
> +        name: "clamav"
tu as pas besoin d'une matrix ici,il y a un seul build

2023-03-06 15:03 UTC, etremblay commented on .github/workflows/docker.yml
> +      REGISTRY: ${{ secrets.GHCR_REGISTRY }}
pour ghcr tu as pris un exemple ailleurs ?

2023-03-06 15:37 UTC, meriouma commented on .github/workflows/docker.yml
> +          registry: ${{ secrets.ECR_REGISTRY }}
Non je ne pense pas qu'on a des exemples avec notre action. On a des repos qui push avec GitHub sur GHCR, mais ça utilise pas nos actions ([exemple](https://github.com/kronostechnologies/docker-mysql2s3/blob/master/.github/workflows/docker-publish.yml)). C'est sûrement pas si compliqué de rajouter le support à notre action.

2023-04-21 13:06 UTC, closed without merging